// The shipped rng profiles — the registry the studio dice and the rng debug
// panel read. The default profile (RANDOM_CURVES wrapped) is always first and
// always what a fresh session rolls; everything else here is selectable in
// the debug panel but read-only, exactly like the default.
//
// ── Shipping a profile tuned in the debug panel ──────────────────────────────
// 1. In the panel (dev build or ?rngdebug), get the profile how you want it.
// 2. Hit "⌗ copy as code" — the clipboard now holds a typed `RngProfile`
//    literal with a slugged, stable id.
// 3. Paste the constant into this file and add it to the list returned by
//    builtinRngProfiles() below.
// 4. `npm test` — rngProfiles.test.ts checks every shipped profile has a
//    unique id and rolls entirely inside its own curve bounds.
// Full workflow, schema and tuning notes: docs/rng-profiles.md.
//
// Ids must be unique and stable (they key localStorage's active-profile pick
// and lock the profile read-only in the panel). Stored dev profiles that
// collide with a shipped id are ignored on load, so shipping can never be
// shadowed by stale browser state.

import { defaultRngProfile, type RandomCurveKey, type RngProfile } from './randomize';
import type { Distribution } from './distributions';

// RNG profile 'built-in copy' — generated by the studio rng debug panel.
// Ship it: paste into rngBuiltinProfiles.ts, add it to builtinRngProfiles(),
// run npm test. Full workflow: docs/rng-profiles.md.
export const BUILT_IN_COPY_RNG_PROFILE: RngProfile = {
	id: 'built-in-copy',
	name: 'built-in copy',
	curves: {
		resolution: {
			kind: 'bimodal',
			meanA: 158,
			stdDevA: 55,
			meanB: 348,
			stdDevB: 81,
			mixA: 0.5,
			min: 51,
			max: 510,
			step: 1
		},
		smoothing: {
			kind: 'gaussian',
			mean: 0.08,
			stdDev: 1.21,
			min: 0,
			max: 4.02,
			step: 1
		},
		tolerance: {
			kind: 'gaussian',
			mean: 0.062,
			stdDev: 0.023,
			min: 0,
			max: 0.129,
			step: 0.01
		},
		minRegionSize: {
			kind: 'gaussian',
			mean: 4,
			stdDev: 5,
			min: 1,
			max: 23.9,
			step: 1
		},
		slicCellSize: {
			kind: 'gaussian',
			mean: 5.4,
			stdDev: 3.3,
			min: 2,
			max: 24,
			step: 1
		},
		slicCompactness: {
			kind: 'gaussian',
			mean: 0.5,
			stdDev: 0.25,
			min: 0,
			max: 1,
			step: 0.02
		},
		penWidthMm: {
			kind: 'gaussian',
			mean: 0.99,
			stdDev: 0.25,
			min: 0.4,
			max: 1.7,
			step: 0.05
		},
		spacingMinMm: {
			kind: 'gaussian',
			mean: 0.12,
			stdDev: 1.09,
			min: 0.05,
			max: 3,
			step: 0.05
		},
		spacingMaxMm: {
			kind: 'bimodal',
			meanA: 2.6667,
			stdDevA: 0.6,
			meanB: 7,
			stdDevB: 1.3,
			mixA: 0.5,
			min: 1.5,
			max: 10,
			step: 0.05
		},
		hatchThreshold: {
			kind: 'gaussian',
			mean: 0.08,
			stdDev: 0.05,
			min: 0,
			max: 0.25,
			step: 0.01
		},
		hatchGamma: {
			kind: 'gaussian',
			mean: 1.7,
			stdDev: 0.45,
			min: 0.8,
			max: 2.8,
			step: 0.05
		},
		inkBoost: {
			kind: 'gaussian',
			mean: 1.16,
			stdDev: 0.22,
			min: 0.79,
			max: 1.75,
			step: 0.05
		},
		layerCount: {
			kind: 'gaussian',
			mean: 2.05,
			stdDev: 0.7,
			min: 1,
			max: 4,
			step: 1
		},
		angleStart: {
			kind: 'gaussian',
			mean: 45,
			stdDev: 70,
			min: -90,
			max: 225,
			step: 5
		},
		angleSpread: {
			kind: 'gaussian',
			mean: 70,
			stdDev: 55,
			min: 0,
			max: 180,
			step: 5
		}
	},
	algorithmWeights: [
		{
			value: 'watershed',
			weight: 4
		},
		{
			value: 'slic',
			weight: 3
		},
		{
			value: 'kmeans',
			weight: 2
		},
		{
			value: 'posterize',
			weight: 2
		}
	],
	channelWeights: [
		{
			value: 'c',
			weight: 3
		},
		{
			value: 'm',
			weight: 3
		},
		{
			value: 'y',
			weight: 3
		},
		{
			value: 'k',
			weight: 2
		},
		{
			value: 'luma-inv',
			weight: 2
		},
		{
			value: 'r',
			weight: 1
		},
		{
			value: 'g',
			weight: 1
		},
		{
			value: 'b',
			weight: 1
		},
		{
			value: 'luma',
			weight: 1
		}
	],
	colors: {
		accentRate: 0.65,
		harmonyWeights: [
			{
				value: 'blue / orange',
				weight: 5
			},
			{
				value: 'teal / red',
				weight: 4
			},
			{
				value: 'purple / yellow',
				weight: 3
			},
			{
				value: 'green / pink',
				weight: 3
			},
			{
				value: 'blue / brown',
				weight: 3
			},
			{
				value: 'red / green',
				weight: 2
			},
			{
				value: 'primary triad',
				weight: 3
			},
			{
				value: 'secondary triad',
				weight: 2
			},
			{
				value: 'blue split',
				weight: 2
			},
			{
				value: 'teal split',
				weight: 2
			},
			{
				value: 'purple split',
				weight: 2
			},
			{
				value: 'pink / teal / yellow',
				weight: 2
			},
			{
				value: 'cool analogous',
				weight: 2
			},
			{
				value: 'warm analogous',
				weight: 2
			},
			{
				value: 'berry analogous',
				weight: 5
			},
			{
				value: 'neutral + red',
				weight: 2
			},
			{
				value: 'neutral + blue',
				weight: 2
			},
			{
				value: 'neutral + teal + orange',
				weight: 2
			}
		]
	},
	layerOverrideChances: {
		penWidthMm: 0.5,
		spacingMinMm: 0.5,
		spacingMaxMm: 0.5,
		threshold: 0.5,
		inkGamma: 0,
		inkBoost: 0.5
	}
};

/**
 * 'uniform sweep' — every curve flattened to a uniform draw over the same
 * min/max. No taste, maximum coverage: it visits the weird corners of the
 * parameter space far more often than the gaussian default, which makes it
 * the profile to roll when hunting for settings combinations that break or
 * surprise. Also the resident example of authoring a profile in code rather
 * than pasting a generated literal.
 */
const uniformSweepProfile = (): RngProfile => {
	const base = defaultRngProfile();
	return {
		...base,
		id: 'uniform-sweep',
		name: 'uniform sweep',
		curves: Object.fromEntries(
			Object.entries(base.curves).map(([key, curve]) => [
				key,
				{ kind: 'uniform', min: curve.min, max: curve.max, step: curve.step }
			])
		) as Record<RandomCurveKey, Distribution>
	};
};

/** All shipped profiles, the default first. Fresh objects on every call. */
export const builtinRngProfiles = (): RngProfile[] => [
	BUILT_IN_COPY_RNG_PROFILE,
	defaultRngProfile(),
	uniformSweepProfile()
];

export const isBuiltinRngProfileId = (id: string): boolean =>
	builtinRngProfiles().some((profile) => profile.id === id);
